# Dependabot will run on day 13 of each month at 01:18 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directories:
      - '**/*'
    schedule:
      interval: 'daily'
      time: '04:17'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 15
    rebase-strategy: 'auto'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    labels:
      - 'dependencies'
      - 'automerge'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 15
    rebase-strategy: 'auto'
    labels:
      - 'dependencies'
      - 'automerge'
